services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'concrete-cloudops/hook-commands']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"