name: Hook Commands
description: Run commands during Buildkite pipeline hooks
author: https://github.com/njlaw
requirements: []
configuration:
  properties:
    preCheckout:
      type: string
    postCommand:
      type: string
    preCommand:
      type: string
  additionalProperties: false
