name: Hook Commands
description: Run commands during Buildkite pipeline hooks
author: https://github.com/njlaw
requirements: []
configuration:
  properties:
    preCommand:
      type: string
  additionalProperties: false
