#!/bin/bash
set -exo pipefail

if [ "z$BUILDKITE_PLUGIN_HOOK_COMMANDS_PRECOMMAND" == "z" ]; then
  echo "Skipping pre-command hook since preCommand configuration not set ..."
  exit 0
fi

/bin/bash -c "$BUILDKITE_PLUGIN_HOOK_COMMANDS_PRECOMMAND"
